### ISSUE TITLE
Support IOV mainnet

### ISSUE THREAD

**Issue by wannabit-yongjoo** [cosmostation/cosmostation-mobile#11]
Support IOV network.
 - generate & manage wallet
 - generate simple tx for IOV chain
 - only support mainnet
 - implement common address feature will go on after this

**Comment by james3387** [comment]
Open

**Comment by wannabit-yongjoo** [comment]
Need to support Starname custom messages

**Comment by wannabit-yongjoo** [comment]
now support StarName(IOV) mainnet.
need more custom module for this chain
