### ISSUE TITLE
Xcode 12.5 in M1 chip pod install error !!!

### ISSUE THREAD

**Issue by shuvayansaha** [cosmostation/cosmostation-mobile#134]
Environment: -

Xcode 12.5
iOS 14.5
Apple M1

**Getting this error in pod installation**

[!] /bin/bash -c 
set -e
sh setup/build_libraries.sh

++ dirname setup/build_libraries.sh
+ SCRIPT_DIR=setup
+ cd setup
+ sh build_secp256k1.sh
++ dirname build_secp256k1.sh
+ SCRIPT_DIR=.
++ mktemp -d
+ TDIR=/var/folders/r0/9d2b5hq57h3_fqnfb733h30m0000gn/T/tmp.EEDw9erv
+ trap '{ cd - ; rm -rf /var/folders/r0/9d2b5hq57h3_fqnfb733h30m0000gn/T/tmp.EEDw9erv; exit 255; }' SIGINT
+ cd /var/folders/r0/9d2b5hq57h3_fqnfb733h30m0000gn/T/tmp.EEDw9erv
+ git clone https://github.com/bitcoin-core/secp256k1.git src
Cloning into 'src'...
++ pwd
+ CURRENTPATH=/var/folders/r0/9d2b5hq57h3_fqnfb733h30m0000gn/T/tmp.EEDw9erv
+ TARGETDIR_IPHONEOS=/var/folders/r0/9d2b5hq57h3_fqnfb733h30m0000gn/T/tmp.EEDw9erv/.build/iphoneos
+ mkdir -p /var/folders/r0/9d2b5hq57h3_fqnfb733h30m0000gn/T/tmp.EEDw9erv/.build/iphoneos
+ TARGETDIR_SIMULATOR=/var/folders/r0/9d2b5hq57h3_fqnfb733h30m0000gn/T/tmp.EEDw9erv/.build/iphonesimulator
+ mkdir -p /var/folders/r0/9d2b5hq57h3_fqnfb733h30m0000gn/T/tmp.EEDw9erv/.build/iphonesimulator
+ cd src
+ ./autogen.sh
./autogen.sh: line 3: autoreconf: command not found

**Comment by wannabit-yongjoo** [comment]
https://stackoverflow.com/questions/64901180/running-cocoapods-on-apple-silicon-m1
