### ISSUE TITLE
Loss of Access to Wallet & Funds 

### ISSUE THREAD

**Issue by Sabertooth101** [cosmostation/cosmostation-mobile#172]
Multiple users are reporting an issue where when prompted to recover / import their wallet on cosmostation, their 24 word mnemonics are yielding 5 different addresses, none of which match their original or contain their funds. Users confirmed that their pathway and seed phrases are fully accurate. As a result, users are unable to access their wallet or funds as their mnemonics are being "linked" by default to different, new addresses

This is a mission critical issue and several users are facing complete loss of funds

**Comment by wannabit-yongjoo** [comment]
support recover key with legacy bitcoinkit lib

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-mobile/pull/183
support with engineer mode
