### ISSUE TITLE
Add contributors for this repo

### ISSUE THREAD

**Issue by kogisin** [cosmostation/cosmostation-mobile#24]
## Add all contributors for this project

**Comment by kogisin** [comment]
@all-contributors please add @wannabit-yongjoo for code, bug, maintenance

**Comment by kogisin** [comment]
@all-contributors please add @kogisin for docs, projectManagement

**Comment by kogisin** [comment]
@all-contributors please add @HeartBreaker for code, bug, maintenance

**Comment by kogisin** [comment]
@all-contributors please add @orkunkl for code

**Comment by kogisin** [comment]
@all-contributors please add @ronaldstoner for bug, doc

**Comment by wannabit-yongjoo** [comment]
close
