### ISSUE TITLE
cosmostation ios bug

### ISSUE THREAD

**Issue by sportsblockchain** [cosmostation/cosmostation-mobile#34]
1.我从binance test 钱包通过Interchain转帐BNB两次到KAVA Testnet钱包，转帐页面显示错误，但是BNB已经减少，而我的KAVA Testnet钱包并没有收到BNB。
![11](https://user-images.githubusercontent.com/55190542/82870170-17047180-9f62-11ea-9652-933b33e8a65c.png)
![12](https://user-images.githubusercontent.com/55190542/82870181-1c61bc00-9f62-11ea-9a68-fdf9bbc72795.png)
![5](https://user-images.githubusercontent.com/55190542/82870243-38655d80-9f62-11ea-98e2-2df9ae7a1f54.png)
![1](https://user-images.githubusercontent.com/55190542/82870259-3dc2a800-9f62-11ea-95d1-5237cd4a4606.png)

2.我之前在CDP Market 创建的抵押借贷债仓，现在消失了。
![13](https://user-images.githubusercontent.com/55190542/82870409-795d7200-9f62-11ea-8ed3-b868f2781ce6.png)
![2](https://user-images.githubusercontent.com/55190542/82870454-909c5f80-9f62-11ea-93cd-aef6a5b6b37c.png)

**Comment by wannabit-yongjoo** [comment]
Hi @sportsblockchain 
Thank you a lot with report.
checked kava-testnet-6000's relayer is not working well. I will check with relayer operator.

**Comment by sportsblockchain** [comment]
> Hi @sportsblockchain
> Thank you a lot with report.
> checked kava-testnet-6000's relayer is not working well. I will check with relayer operator.

Hello, I have re-downloaded and it's working fine now.

**Comment by wannabit-yongjoo** [comment]
HI! checked  testnet relayer has been downed.
now It's recovered and work well as you checked. 

Thanks a lot for reporting!
