### ISSUE TITLE
Passphrase should indicate sequence

### ISSUE THREAD

**Issue by Tosch110** [cosmostation/cosmostation-mobile#35]
When creating a new wallet for a SDK chain, the passphrase is shown to the user to be written down.

The sequence for the passphrase should be shown (e.g. 1. arm 2. bolt 3. underneath 4....)

Else the user might not be aware if he should read the passphrase from top to bottom, from left to right or even arabic from right to left. Which could result in serious losses.

**Comment by wannabit-yongjoo** [comment]
HI @Tosch110 
Thanks a lot for reporting.
We gonna start make new UI for mnemonics numbering

**Comment by wannabit-yongjoo** [comment]
@thaidout  
Please check this issue & make concept UI with Ryung

**Comment by wannabit-yongjoo** [comment]
Android side update
https://github.com/cosmostation/cosmostation-mobile/commit/6a308df60a5a17c46524a6409f383afeb73945e6
![스크린샷 2020-06-24 오후 2 03 09](https://user-images.githubusercontent.com/38899600/85502941-728a5380-b623-11ea-8680-a5f4ba3257f5.png)
![스크린샷 2020-06-24 오후 1 39 10](https://user-images.githubusercontent.com/38899600/85502953-774f0780-b623-11ea-8193-c4a6fe9571d0.png)

**Comment by wannabit-yongjoo** [comment]
iOS side updated
https://github.com/cosmostation/cosmostation-mobile/commit/aaabe70410dc30ff8a993bd9e80e7a93db97b19c

![스크린샷 2020-06-24 오후 5 12 40](https://user-images.githubusercontent.com/38899600/85520961-8ee7b980-b63e-11ea-9ae0-c72eab631e15.png)
![스크린샷 2020-06-24 오후 5 13 38](https://user-images.githubusercontent.com/38899600/85520965-9018e680-b63e-11ea-9f45-ecdfa4d02a1c.png)

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-mobile/commit/0fd4d5d00a33cd8fbf21a6e4b6731708f5ab23d5
