### ISSUE TITLE
Band option missing on delete and restore of wallet

### ISSUE THREAD

**Issue by cryptorico** [cosmostation/cosmostation-mobile#44]
The option to import a Band wallet disappears if the wallet is deleted and re-imported using IOS 13.5.1 on iPhone 8+

**Comment by cryptorico** [comment]
Same issue on a fresh install of the app and selecting import. No option to select Band.

**Comment by wannabit-yongjoo** [comment]
Hi @cryptorico 
Thanks a lot for reporting!.
We fixed it and release it next version.

https://github.com/cosmostation/cosmostation-mobile/commit/88eb5df6779a184c8c4bcbf2afa2c790edab7f73
