### ISSUE TITLE
Hello, xcode 11 can't run, how to solve it.

### ISSUE THREAD

**Issue by abu0306** [cosmostation/cosmostation-mobile#5]
Hello, macOS 10.15 xcode 11  can't run the project, how to solve it.

[https://upload-images.jianshu.io/upload_images/10107766-34f7442f8ce4a669.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240](url)
[https://upload-images.jianshu.io/upload_images/10107766-135493c97ed25fa0.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240](url)

**Comment by wannabit-yongjoo** [comment]
Dear @abu0306 

As integrated Binance libanray there is some conflict.
I updated readme file, so now you can build locally.
Thank you for issue.

**Comment by abu0306** [comment]
Thanks！

**Comment by liu-zhipeng** [comment]
Hello, abu0306. How did you fix? 

Have you met following issue when installing BitcoinKit? 

+ xcrun lipo -create /var/folders/vg/bls_nkjs7_jclq8_brh9tfmw0000gn/T/tmp.6MLaJnPf/.build/iphoneos/lib/libsecp256k1.a /var/folders/vg/bls_nkjs7_jclq8_brh9tfmw0000gn/T/tmp.6MLaJnPf/.build/iphonesimulator/lib/libsecp256k1.a -o ./../Libraries/secp256k1/lib/libsecp256k1.a
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /var/folders/vg/bls_nkjs7_jclq8_brh9tfmw0000gn/T/tmp.6MLaJnPf/.build/iphoneos/lib/libsecp256k1.a and /var/folders/vg/bls_nkjs7_jclq8_brh9tfmw0000gn/T/tmp.6MLaJnPf/.build/iphonesimulator/lib/libsecp256k1.a
