### ISSUE TITLE
Unable to resolve dependency : Could not resolve project :lib.

### ISSUE THREAD

**Issue by liu-zhipeng** [cosmostation/cosmostation-mobile#51]
When I synchronize gradle module, it shows following error. 

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :lib.
Show Details
Affected Modules: app

This error comes from build.gradle(app). 

dependencies {
    implementation project(path: ':lib')
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    ... ...
}

How should I fix this error?

**Comment by liu-zhipeng** [comment]
I added wallet connect module to project. It worked correctly.

**Comment by sambarboza** [comment]
I'm also getting this error, @liu-zhipeng, could you please elaborate a bit more on your solution?
| I added wallet connect module to project. It worked correctly.

Where can I find this missing lib?
