### ISSUE TITLE
Kava wallet not detected on BNB interchain transfer

### ISSUE THREAD

**Issue by PochenriederAlex** [cosmostation/cosmostation-mobile#52]
### Summary

Kava wallet is not detected when trying to make an interchain transfer from BNB Wallet.

### Steps to reproduce

1. Create KAVA and BNB wallet.
2.  Go to BNB Wallet and select interchain transfer.
3. Select KAVA Chain on Destination Chain and press next.
4. Confirm popup.
5. Try to select your Kava account on Recipient Address input.

### Expected result
Kava address is shown and you can continue with the following steps.

### Current result
A Popup opens saying "No kava-3 Account" preventing me from continue.

### More info

- OS: Android 9
- Version: 1.3.10.
- Bnb wallet with funds.
- Neither new created Kava wallets nor Imported from seed ones are detected.

**Comment by wannabit-yongjoo** [comment]
HI @PochenriederAlex
Thanks a lot for bug reporting.

Even if user made a Kava wallet, user can't request swap cuz that's empty account!.
(empty means not balance zero, but no chain's account number) 
without account number you can't  broadcast ClaimSwapTx.


![스크린샷 2020-08-07 오후 1 39 38](https://user-images.githubusercontent.com/38899600/89609971-4b76a100-d8b4-11ea-9bc9-515902c3082d.png)
After create Kava wallet, user can request airdrop just tiny kava coin.
if this account receive tiny kava coin, this account get account number form chain, than process swap func.

I wish this message could be help to you.
Than please close this issue.
If it is of any other kind problem, please leave a message

**Comment by PochenriederAlex** [comment]
Thanks! It worked like a charm. I'm closing the issue.

**Comment by wannabit-yongjoo** [comment]
After talking Kava chain guys, relayer updated 
user can claim bep3 swap without no account number.
empty(no account number) account can claim swap now.

So this issue is valid and updated with 
https://github.com/cosmostation/cosmostation-mobile/commit/cf8b8b920b94fd50c7135c55a053ae6ec65f1623
https://github.com/cosmostation/cosmostation-mobile/commit/c3ccf51163d9f8331633469f908c2bebcca2c8a7
