### ISSUE TITLE
BNB interchain transfer steps can be skipped by clicking next several times

### ISSUE THREAD

**Issue by PochenriederAlex** [cosmostation/cosmostation-mobile#53]
### Summary
BNB-Kava interchain transfer allows the user to skip steps by clicking several times in the first Next button.

### Steps to reproduce

1. Go to BNB Wallet and select interchain transfer.
2. Select KAVA Chain on Destination Chain and press next several consecutive times.
3. Confirm popups.

### Current result
Several popups opens and every confirm skip a step allowing the user to get to the last step, skipping validations and without putting any value in any step.

### Expected result
- Only one popup opens, and confirmation gets you only to the first step.
- Button gets blocks after first click.

### More info
- OS: Android 9
- Version: 1.3.10.

**Comment by wannabit-yongjoo** [comment]
HI @PochenriederAlex 
Thanks for reporting!  

I understood as 
"BNB-BEP3 Swap Supplies" popups opened many times, and click each "confirm" button makes go next, next page without validating! 

I tested a lot but can't not reproduce now, but I and QA team will tracking this continuously!
and then we can add guard code.

Thanks a lot once more

**Comment by PochenriederAlex** [comment]
Exactly, that's the issue.
In my case, when i click in the first next button, the "BNB-BEP3 Swap Supplies" takes some time to appear (probably because i'm in a slow network), and that's why i can click next several times and therefore opening several popups. 

Here's an example of the popup in the third step:
![Screenshot_20200807-092244](https://user-images.githubusercontent.com/36549859/89645282-d2655280-d88f-11ea-81ea-90da5e5217e1.png)
