### ISSUE TITLE
 I still don’t understand how swift should date

### ISSUE THREAD

**Issue by GarkiOS** [cosmostation/cosmostation-mobile#70]
What are the steps to introduce cocoapods or other methods? I only need to use the function of generating cosmos address, the private key and public key are using HDWalletKit and not BitcoinKit

**Comment by wannabit-yongjoo** [comment]
Hi @GarkiOS 
You can also get cosmos address with only using HDWalletKit.
Im using BitcoinKit for easy to generate signature.

You can derive child key as bep44 path with masterkey in HDWalletKit.
(cosmos case m/44'/118'/0'/0/X)

then with your child public key(bytes) you can generate cosmos address
(you need ripemd160 to gen addesss)
https://github.com/cosmostation/cosmostation-mobile/blob/master/Cosmos-IOS/Cosmostation/Cosmostation/Utils/WKey.swift#L81

Hope this helps.
