### ISSUE TITLE
where is web-version and electron one?

### ISSUE THREAD

**Issue by Kwaskoff** [cosmostation/cosmostation-mobile#79]
Guys, I can't find repository of your web wallet
and I really need stand alone version, like chromium based electron 
thx

**Comment by Booyoun-Kim** [comment]
Hi @Kwaskoff 😁. We are developing the web-version 2. However we might be not decide that web wallet become open source. We will discuss it with our team. 

If you need your own wallet, you would like to create one using cosmosjs(https://github.com/cosmostation/cosmosjs). You can create an address, send ATOM etc.

**Comment by Kwaskoff** [comment]
> Hi @Kwaskoff grin. We are developing the web-version 2. However we might be not decide that web wallet become open source. We will discuss it with our team.
> 
> If you need your own wallet, you would like to create one using cosmosjs(https://github.com/cosmostation/cosmosjs). You can create an address, send ATOM etc.

I'm not developer, I just use your wallet. If you are developing the web-version 2, may be you can publish the web-version 1 in electron =)

**Comment by Booyoun-Kim** [comment]
I will tell to publish electon version to our team. However we are focusing on web wallet. We will discuss about it. Thank you.
