### ISSUE TITLE
Application crashed on Kava CDP & Harvest Market

### ISSUE THREAD

**Issue by dualsystems** [cosmostation/cosmostation-mobile#81]
On CDP Market tab when click on any CDP screen refresh and return at main screen. 
On harvest tab when click on any deposit, application be crashed.

OS: Android

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-mobile/commit/7e33dbcdbe70e7ef40a707eb0836d7d9eeef2ec1
