### ISSUE TITLE
Incorrect staking rewards

### ISSUE THREAD

**Issue by kuzkula** [cosmostation/cosmostation-mobile#83]
Hello! While using Keplr on Chrome, if you view your SIF from the drop-down, and then go back to ATOM, the APY goes into crazy mode stating you can earn like 4,xxx,xxx%. A small bug, but I found one!

**Comment by wannabit-yongjoo** [comment]
HI @kuzkula 
I think this issue with Kelpr..not cosmostaion app.
You can make issue "https://github.com/chainapsis/keplr-extension"
