### ISSUE TITLE
Memo option is misleading

### ISSUE THREAD

**Issue by serge1peshcoff** [cosmostation/cosmostation-mobile#98]
https://github.com/cosmos/cosmos-sdk/issues/9122
TLDR: users can put mnemonic as memo and expose their wallets.

Two things can be done here:
1) renaming memo to note, the same way it was done in the cosmos-sdk
2) checking if the string passed as memo is bip39 valid mnemonic, if so, either disallowing the transaction or asking user if that's what they really want.

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-mobile/commit/9f7b869c86a2ffede5db856c68708db14cfe597a
https://github.com/cosmostation/cosmostation-mobile/commit/081e712518ae9d5d89e267106171fd3b7bb84085
https://github.com/cosmostation/cosmostation-mobile/commit/451202ce1a38b5ef565ad3fc7a20eb5d54599f41
