### ISSUE TITLE
Crypto.org typo

### ISSUE THREAD

**Issue by fgallaire** [cosmostation/cosmostation-mobile#99]
Many occurences of `CRYTO.ORG` (lacking **P**) in the source code.

**Comment by wannabit-yongjoo** [comment]
https://github.com/cosmostation/cosmostation-mobile/commit/fb913a7f88e32f87380d4efd72649a23cb5ca883
https://github.com/cosmostation/cosmostation-mobile/commit/d11e51afdf260f77f2385b23d66ef1658301a654
